completed assessment
learn-academy-2019-delta/javascript-intro-assessment-1-Josh3845 pull request #1
Opened 2019-08-07 00:10 UTC by Josh3845

2019-08-07 17:25 UTC, DanteCypress requested changes

2019-08-07 17:25 UTC, DanteCypress commented on js-intro.js
> +console.log(pet)
Hey Josh, logic is sound. Let's put this into a function now. We can do this by:
ES5: `function intoArr(str,str2){
}`
ES6: `const intoArr = (str,str2) =>{
}`

2019-08-07 17:25 UTC, DanteCypress commented on js-intro.js
> +// console.log(lower(myDog,myCat))
Hey Josh,
Let's think about why we're using an if statement here? What if dog1 wasn't Snoopy, then it wouldn't return `dog1.toLowerCase()`. Consider removing the `if` statement or beefing up the `if` statement to look at the case sensitive cases.

2019-08-07 17:25 UTC, DanteCypress commented on js-intro.js
> +}
Hey Josh, you're on to something here. Consider the following:
What do you want to do with the values in your array, before you join the array back together? Below I have added a template for a function, you just need to fill it in with the logic
```
const noVowels = (str) =>{
 let yup = str.split('')

 for(let i =0; i<yup.length;i++){
     if(){

     }
 }
}
```

2019-08-07 17:25 UTC, DanteCypress commented on js-intro.js
> +console.log(cats(toonimals));
Hey Josh, Consider the following:
```
let ifCat = (listOfToonimals) => {
     let arr = []
     listOfToonimals.forEach(function (toonimal){
         if(toonimal.animal=="cat"){
             arr.push(toonimal)
         }
     })
  
     return arr
 }
console.log(ifCat(toonimals));
```

2019-08-07 17:25 UTC, DanteCypress commented on js-intro.js
> +console.log(cats(toonimals));
Hey Josh, look above and see if you can solve this problem. Make sure to look up any methods or high-order function you need clarification on

2019-08-12 16:34 UTC, sjproctor approved these changes
Nice work! Those changes look good. Go ahead and merge your code.

2019-08-13 17:30 UTC, merged